# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8fa0bea65000048383081bc1938e2e332941616cd826652bf3b7dba083449c9c1315e7609130977b6d8b9c87a327a14e15a64e3db994c51760b7ada2e8df386f

test:
  secret_key_base: 8cc81469b7ce9725d4ba9b2610361496225466057e5fef6f6217ea517b7304a1bff07ac4cbb53d27e669a76df57e85eaf6a5f70f4e27356a030565f9f40c72aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
